# Generated by Django 5.1.2 on 2024-10-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_label_printed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='unique_number',
        ),
    ]
