# Generated by Django 5.1.2 on 2024-10-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_label_unique_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='custom_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
