# Generated by Django 5.1.2 on 2024-10-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_label_custom_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldata',
            name='is_printed',
        ),
        migrations.RemoveField(
            model_name='label',
            name='is_printed',
        ),
        migrations.RemoveField(
            model_name='label',
            name='printed_at',
        ),
        migrations.RemoveField(
            model_name='label',
            name='printed_by',
        ),
    ]
